# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f16edf5b91947d0dde1af0b55927d8d1894f03240854bfdcea75178a16cf459a38139cd65b473d3046fc965b8bfa5b4b37e3175d0cc8440ee8d60edffe367080

test:
  secret_key_base: d1dab148fa07863a261c2283859913951b6e02f3d2d8f40a81d178037cf66bb8169e2e183c5e82a87a4a3ec1e871ed4f8de259496e80470e17257db7113f48ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
